claim_key: 7e9c778a62485237fd0ad78f011ca77d
auth_tokens:
  cam01: DISABLED_e494ffba91cc8d29
  cam02: cam2q1w2e3r4t5y6u7i8o9p0
storage:
  base_dir: /home/pi/data
  clips_subdir: clips
  min_free_percent: 10
database: /home/pi/data/hub.db
