hub_url: http://192.168.0.150:5000
node_id: cam01
auth_token: b8bc8587969a2488d8bba9ec6feaae71
profile: action_1080p50
bitrate_kbps: 22000
rotation: 180
sensor:
  threshold_mm: 1800
  debounce_ms: 200
  xshut_gpio: 4
recording:
  resolution: 1920x1080
  framerate: 50
  duration_s: 8
  bitrate_kbps: 22000
  rotation: 180
storage:
  min_free_percent: 10
heartbeat_interval_sec: 10
autofocus:
  strategy: continuous_lock_on_record
  range: normal
  speed: fast
  roi_norm:
  - 0.0
  - 0.5
  - 1.0
  - 0.3
profiles:
  balanced_1080p30:
    resolution: 1920x1080
    fps: 30
    gop: 60
    h264_profile: high
    h264_level: '4.1'
    default_bitrate_kbps: 14000
    recommended_bitrate_kbps:
    - 12000
    - 18000
    default_rotation: 0
  action_1080p50:
    resolution: 1920x1080
    fps: 50
    gop: 100
    h264_profile: high
    h264_level: '4.2'
    default_bitrate_kbps: 24000
    recommended_bitrate_kbps:
    - 22000
    - 28000
    default_rotation: 0
  storage_saver_720p30:
    resolution: 1280x720
    fps: 30
    gop: 60
    h264_profile: high
    h264_level: '4.0'
    default_bitrate_kbps: 7000
    recommended_bitrate_kbps:
    - 6000
    - 10000
    default_rotation: 0
  night_low_noise_1080p30:
    resolution: 1920x1080
    fps: 30
    gop: 60
    h264_profile: high
    h264_level: '4.1'
    default_bitrate_kbps: 18000
    recommended_bitrate_kbps:
    - 16000
    - 22000
    default_rotation: 0
  smooth_720p60:
    resolution: 1280x720
    fps: 60
    gop: 120
    h264_profile: high
    h264_level: '4.1'
    default_bitrate_kbps: 12000
    recommended_bitrate_kbps:
    - 10000
    - 16000
    default_rotation: 0
